### ISSUE TITLE
スタート画面とゲーム画面のサイズ

### ISSUE THREAD

**Issue by kouki0412** [C0A21007/ProjExD#12]
https://github.com/C0A21007/ProjExD/blob/3794dbff56f343d629b102153ad946bc7811a298/ex04/dodge_bomb.py#L117

スタート画面とゲーム画面のサイズが大きく違っているのを修正した方が良いかもしれません。

**Comment by C0A21007** [comment]
コメントありがとうございます。スタート画面のサイズはそこまで大きくなくて良いと考えたためこのようになっています。
